version: "3.7"
services:
  php:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: >
      sh -c "
        ./composer install &&
        npm run dev &&
        ./artisan --host=0.0.0.0 serve
      "
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: hardpass
      POSTGRES_DB: forum
