version: "3.7"
services:
  php:
    image: php:7.4-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: >
      sh -c "
        if [ ! -f /app/composer ]; then
          wget -qO- https://getcomposer.org/installer | php -- --install-dir=/app --filename=composer;
        fi && \
        ./composer install && \
        ./artisan --host=0.0.0.0 serve
      "
